# Generated by Django 4.1.3 on 2022-11-25 17:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
