# Generated by Django 4.1.3 on 2022-11-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Débito', 'Debito'), ('Boleto', 'Boleto'), ('Crédito', 'Credito'), ('Financiamento', 'Fin'), ('Recebimento Empréstimo', 'Rec Emp'), ('Vendas', 'Vendas'), ('Recebimento TED', 'Ted'), ('Recebimento DOC', 'Doc'), ('Aluguel', 'Alug')], default='Débito', max_length=100)),
                ('date_of_currence', models.CharField(max_length=8)),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_store', to='stores.store')),
            ],
        ),
    ]
