# Generated by Django 4.1.3 on 2022-11-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements_store', '0002_alter_movementstore_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementstore',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
