# Generated by Django 4.1.3 on 2022-11-25 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movements_store', '0002_rename_store_name_movementstore_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementstore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
