# Generated by Django 4.1.3 on 2022-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
