# Generated by Django 4.1.3 on 2022-11-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
